
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postdb
    username: jukyung
    password: pass
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        format_sql: true
    show-sql : true

jwt:
  secret-key: fast-campus.simple_sns_2022_secret_key
  token.expired-time-ms : 2592000000
